feat: create phone number component  tckt-363
GSA-TTS/forms pull request #382
Opened 2024-11-13 01:39 UTC by kalasgarov

Created Phone Number Pattern for Forms Users.
Created Phone Number Pattern Edit for Form Builders.
Added unit tests for Phone Number config file.

2024-11-13 17:00 UTC, danielnaab requested changes
I just have a couple comments, but this looks great.

2024-11-13 20:22 UTC, kalasgarov commented on packages/design/src/Form/components/PhoneNumber/PhoneNumber.tsx
> +          className="usa-input margin-bottom-1"
Updated!

2024-11-13 20:22 UTC, kalasgarov commented on packages/forms/src/error.ts
> +  | undefined;
Updated!

2024-11-15 15:17 UTC, danielnaab approved these changes
Approved. I noticed an error class missing from an input (to fix before merging) but otherwise looks great.

2024-11-15 16:21 UTC, kalasgarov commented on packages/design/src/FormManager/FormEdit/components/PhoneNumberPatternEdit.tsx
> +            className="usa-input"
Updated!

2024-11-15 16:30 UTC, merged